### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by papower1** [marekrei/convertvec#6]
I want to collect some useful word2vec related projects to one.
And want to do some to use easily for everyone.

This is my repo.
https://github.com/papower1/word2vec_addons

If you want to. Please reply.

regards.

**Comment by marekrei** [comment]
Sorry, I'm not quite sure what you're asking.
If you want to include convertvec.c into your repository, that's fine. Just please leave in the information that I'm the author and include a link to the original repository in your readme. Thanks!

**Comment by papower1** [comment]
That's exactly what I want. Thanks. I'll link your repo and your id.

**Comment by mossaab0** [comment]
@marekrei Can you please include a License file? Something like what Mikolov has done would be useful. Thanks!

https://github.com/tmikolov/word2vec/blob/master/LICENSE

**Comment by marekrei** [comment]
Done
